reverse-map:
  - "/hoge/:http://localhost:8501"
#host: http://hogehoge:8080
port: 8080
home: "/"
mail:
  host: localhost:19925
  from: sample@sample.com 
  user:
  pass:
  validedlist:
    - foo@example.com
logging: 
  enabled : true
  filename : ./log/access.log